var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                           xxx  ",
   "  xxx                                                                        x  ",
   "  x                                                                          x  ",
   "  x                              D               DD                          x  ",
   "  x                             DDD             DDDDD                        x  ",
   "  x                              D                                           x  ",
   "  x                                           !  !                           x  ",
   "  x                                         x!!!x!x         DDD          !!! x  ",
   "  x             DDDD                 !! o   xxxxxxx                     x!v!!x  ",
   "  x                                xxxxxx   xxxxxxx                oo        x  ",
   "  x                       xxxx     xxxxxx   xxxxxxx                          x  ",
   "  x                  oo   xxxx     xxxxxx   xxxxxxx   !!  !       !xx!x  xxx x  ",
   "  x                 xxxx  xxxx     xxxxxx   xxxxxxxxxxxxxxx       !!!!!   x  x  ",
   "  x                 xxxx  xxxx     xxxxxx   xxxxxxxxxxxxxxx       !!!!!   x  x  ",
   "  x          xxxx   xxxx  xxxx     xxxxxx   xxxxxxxxxxxxxxx       !!!!!   x  x  ",
   "  x  @       xxxx   xxxx  xxxx     xxxxxx   xxxxxxxxxxxxxxx       !!!!!   x  x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "  xxxxxxxxxxxx                                                                  ",
   "  xxxx  @ xxxx                                                    xxxxxxxxxxxx  ",
   "  x=         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       x          x  ",
   "  xxxx    xxxx                            x                       x          x  ",
   "  x         =x                            x     xxxxxxxxxxxxxxxxxxx          x  ",
   "  xxxx        o                           x     x              D             x  ",
   "  x         xxxxxxxxx      D              x     x                            x  ",
   "  xxx        x      x      D              x     x DD                         x  ",
   "  x!!!|!!!!!!x      x                     x     x                            x  ",
   "  x!!!!!!!!!!x      x                     x     x                   o        x  ",
   "  x!!!!!|!!!!x      x      o            z x     x            xxx          xxxx  ",
   "  xxxxxxxxxxxx      x                 xxxxx     xxx          x  !!!!!!!!!!      ",
   "                    xxxx        DD        x     x            x  !!!!!!!!!!      ",
   "                    x                     xxxxxxx            x  !!!!!!!!!!      ",
   "                    x                                      xxx  !!!!!!!!!!      ",
   "                    x         o       =       o      =       x  !!!!!!!!!!      ",
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxx      ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "]]
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
